#setwd("~/autocross/autocross")
#setwd("C:/Users/kbo/Documents/autocross/autocross")
if ("package:autocross" %in% search())
  detach('package:autocross')
if ("autocross" %in% loadedNamespaces())
  unloadNamespace("autocross")
so_file <- file.path("src", "autocross.so")
if (file.exists(so_file))
  file.remove(so_file)
library(devtools)
devtools::build()
devtools::document()
install.packages("~/autocross/autocross_2025-1.0.tar.gz", repos=NULL, type="source")
library(autocross)
