if ("package:autocross" %in% search())
  detach('package:autocross')
if ("autocross" %in% loadedNamespaces())
  unloadNamespace("autocross")
so_file <- file.path("src", "autocross.so")
if (file.exists(so_file))
  file.remove(so_file)
library(devtools)
tarball <- devtools::build()
devtools::document()
install.packages(tarball, repos=NULL, type="source")
library(autocross)
