setwd('~/drive/autocross')
data = read.table('test_data.txt', col.names=c('time', 'x.series', 'y.series'))
source('R/estimate_CI.R')
dyn.unload('pearsont3sub.so')
dyn.load('pearsont3sub.so')
print(data$time)
result = estimate_CI(data$time, data$x.series, data$y.series)
dyn.unload('prufa.so')
dyn.load('prufa.so')
n = as.integer(2)
x = c(2.0, 3.0)
y = c(4.0, 5.0)
sum = double(1)
.Fortran('prufa', n, x, y, sum)

print(result)
