setwd('~/drive/autocross')
data = read.table('test_data.txt', col.names=c('time', 'x.series', 'y.series'))
if (is.loaded('pearsont3sub')) dyn.unload('pearsont3sub.so')
if (is.loaded('ss')) dyn.unload('ss.so')
dyn.load('pearsont3sub.so')
dyn.load('ss.so')
print(data$time)
source('R/estimate_CI.R')

result = estimate_CI(data$time, data$x.series, data$y.series)
str(result)
if (is.loaded('prufa')) dyn.unload('prufa.so')
dyn.load('prufa.so')
n = length(data$x.series)
summa = double(1)
.Fortran('prufa', n, data$x.series, data$y.series, summa)
print(paste('summa=', summa))

